networks:
  proxy:
    external: true

services:
  web-nrsafe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-nrsafe
    restart: unless-stopped
    networks:
      - proxy

    healthcheck:
      test: ["CMD-SHELL","grep -q ok /usr/share/nginx/html/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.web-nrsafe.rule: Host(`web.nrsafe.app.br`)
      traefik.http.routers.web-nrsafe.entrypoints: websecure
      traefik.http.routers.web-nrsafe.tls.certresolver: le
      traefik.http.services.web-nrsafe.loadbalancer.server.port: "80"
