name: Deploy Frontend NRSAFE na VPS

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Definir versao pela tag
        run: |
          set -e
          VERSION="$(git describe --tags --exact-match)"
          VERSION="${VERSION#v}"
          echo "Versao detectada: $VERSION"
          sed -i "s/version: \".*\"/version: \"${VERSION}\"/" src/environments/environment-prod.ts

      - name: Instalar dependências
        run: npm ci

      - name: Build do frontend
        run: npm run build -- --configuration=production

      # Se quiser rodar testes/lint:
      # - name: Rodar testes
      #   run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Deploy na VPS via SSH (branch automática)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            set -e

            BRANCH="${{ github.ref_name }}"

            echo "Deployando branch: $BRANCH"

            cd /opt/app/nrsafe/web-app/front/NRSafe-front

            git fetch origin
            git checkout $BRANCH
            git pull origin $BRANCH

            ./deploy.sh
